version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  web:
    build: .
    depends_on:
      - mysql
    ports:
     - "80:80"
    image: web
    volumes:
      - sites:/var/www
    restart: always