version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql
    container_name: mysql_d8
    restart: always

  apache:
    build: .
    depends_on:
      - mysql
    ports:
      - "8088:80"
      - "445:443"
    image: apache
    volumes:
      - ./sites:/var/www
      - ./certs:/etc/apache2/certs
    container_name: apache_d8
    restart: always
